FROM nvcr.io/nvidia/tensorrt:25.08-py3

WORKDIR /app

RUN python3 -m pip install --no-cache-dir \
    fastapi \
    "uvicorn[standard]" \
    pydantic \
    requests \
    numpy

COPY api ./api
COPY inference ./inference

COPY docker/entrypoint.gpu.sh /app/entrypoint.gpu.sh

RUN chmod +x /app/entrypoint.gpu.sh

ENV ACCELSERVE_BACKEND=tensorrt
ENV ACCELSERVE_ENGINE_PATH=/app/inference/accelserve_mlp_fp16.engine

EXPOSE 8000

ENTRYPOINT ["/app/entrypoint.gpu.sh"]