FROM nvcr.io/nvidia/tensorrt:25.08-py3

WORKDIR /app

COPY requirements.txt .

RUN python3 -m pip install --no-cache-dir \
    fastapi \
    "uvicorn[standard]" \
    pydantic \
    requests \
    numpy

COPY api ./api
COPY inference ./inference

EXPOSE 8000

CMD ["python3", "-m", "uvicorn", "api.server:app", "--host", "0.0.0.0", "--port", "8000"]